# Generated by Django 3.2.3 on 2024-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240721_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
