# Generated by Django 3.2.3 on 2024-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=126, verbose_name='Пароль'),
        ),
    ]
