# Generated by Django 3.2.3 on 2024-08-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240725_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
