version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: annagulyaeva/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/

  frontend:
    image: annagulyaeva/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    container_name: foodgram-proxy
    image: annagulyaeva/foodgram_gateway
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/app/media/
