# Generated by Django 3.2.3 on 2024-08-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_auto_20240827_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'default_related_name': 'shopping_lists', 'ordering': ('recipe__name',), 'verbose_name': 'список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
