# Generated by Django 3.2.3 on 2024-08-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'default_related_name': 'follows', 'verbose_name': 'подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
