# Generated by Django 3.2.3 on 2024-08-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorites', 'ordering': ('recipe__name',), 'verbose_name': 'избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
