# Generated by Django 3.2.3 on 2024-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240827_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Название'),
        ),
    ]
